# top level stuff you probably don't need to touch
#highlighter: pygments
#markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://mhaidarhanif.com
baseurl: /
author: M Haidar Hanif
nick: Haidar
title: M Haidar Hanif | Open Strategy & Technology Integrator
description: Helping people to be integrated and insightful, so that humanity can grow and thrive in the right place for good.
avatar: avatar.jpg
email: "&#109;&#101;&#64;&#109;&#104;&#97;&#105;&#100;&#97;&#114;&#104;&#97;&#110;&#105;&#102;&#46;&#99;&#111;&#109;"
search: m+haidar+hanif
googleplus: +MHaidarHanif
linkedin: mhaidarhanif
facebook: mhaidarhanif
twitter: mhaidarh
github: mhaidarh
keybase: mhaidarh
#stackoverflow: users/333346/m-haidar-hanif
#disqus: username
google_analytics: UA-27817850-1

# needed for travis-ci build
exclude: [vendor]
